from __future__ import annotations

import re
import unicodedata
from collections import Counter
from dataclasses import dataclass

from rag.indexer.chunking.structured import ChunkedDocument, StructuredChunkerProtocol


def clean_content_text(text: str) -> str:
    """Nettoyage non-destructif du texte avant chunking.

    Opérations (dans l'ordre) :
    1. Normalisation unicode NFKC — ligatures, espaces spéciaux, apostrophes
    2. CRLF / CR → LF
    3. Suppression des espaces et tabulations en fin de ligne
    4. Maximum 2 lignes vides consécutives

    L'indentation (espaces en début de ligne) est intégralement préservée —
    elle est sémantique pour le code Python/YAML/… Pas de normalisation des
    espaces en milieu de ligne (idem).
    """
    text = unicodedata.normalize("NFKC", text)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text


_SEP_LINE_RE = re.compile(r"^[ \t]*[-=*~_]{3,}[ \t]*$")


def _is_separator_line(line: str) -> bool:
    return bool(_SEP_LINE_RE.match(line))


def strip_decorative_separators(text: str) -> str:
    """Supprime les lignes séparatrices décoratives (---, ===, ***, ~~~, ___).

    Préserve les underlines setext Markdown (--- ou === immédiatement après une
    ligne de texte non vide et non-séparateur) pour ne pas casser la détection
    de titres H1/H2.
    """
    lines = text.split("\n")
    result: list[str] = []
    for i, line in enumerate(lines):
        if _is_separator_line(line):
            prev = lines[i - 1] if i > 0 else ""
            if prev.strip() and not _is_separator_line(prev):
                result.append(line)  # underline setext → préservé
        else:
            result.append(line)
    return "\n".join(result)


_HTML_TAG_RE = re.compile(r"<[^>]+>")
_NAMED_ENTITIES: dict[str, str] = {
    "&amp;": "&",
    "&lt;": "<",
    "&gt;": ">",
    "&quot;": '"',
    "&apos;": "'",
    "&nbsp;": " ",
}
_NUMERIC_ENTITY_RE = re.compile(r"&#(?:\d+|x[0-9a-fA-F]+);")


def strip_html_tags(text: str) -> str:
    """Supprime les balises HTML et décode les entités communes.

    Opérations (dans l'ordre) :
    1. Remplacement des entités nommées (&amp;, &lt;, &gt;, &quot;, &apos;, &nbsp;)
    2. Suppression des entités numériques (&#123;, &#x7f;)
    3. Suppression des balises (<tag>, </tag>, <self/>)
    """
    for entity, char in _NAMED_ENTITIES.items():
        text = text.replace(entity, char)
    text = _NUMERIC_ENTITY_RE.sub("", text)
    return _HTML_TAG_RE.sub("", text)


_BOILERPLATE_RE = re.compile(
    r"auto[- ]?generated"
    r"|do\s+not\s+edit"
    r"|generated\s+by\b"
    r"|this\s+file\s+(?:was|is)\s+(?:auto[- ]?)?generated"
    r"|do\s+not\s+modify"
    r"|spdx-license-identifier"
    r"|spdx-filecopyrighttext"
    r"|copyright\s*\(c\)"
    r"|all\s+rights\s+reserved",
    re.IGNORECASE,
)
_REPEAT_THRESHOLD = 5
_REPEAT_MIN_LEN = 10


def strip_boilerplate_lines(text: str) -> str:
    """Supprime les lignes boilerplate : marqueurs connus + lignes répétées.

    Passe 1 — marqueurs connus (insensible à la casse) :
        auto-generated, do not edit, generated by, SPDX-*, copyright (c),
        all rights reserved, …

    Passe 2 — en-têtes/pieds de page répétés :
        Toute ligne non indentée d'au moins 10 caractères apparaissant 5 fois
        ou plus dans le même document est retirée (heuristique footer/header).
    """
    lines = text.split("\n")
    filtered = [ln for ln in lines if not _BOILERPLATE_RE.search(ln)]
    candidates = [
        ln
        for ln in filtered
        if ln.strip() and not ln[:1].isspace() and len(ln.strip()) >= _REPEAT_MIN_LEN
    ]
    repeated = {ln for ln, n in Counter(candidates).items() if n >= _REPEAT_THRESHOLD}
    if repeated:
        filtered = [ln for ln in filtered if ln not in repeated]
    return "\n".join(filtered)


@dataclass(frozen=True)
class CleaningOptions:
    """Options de nettoyage du contenu avant chunking.

    Chaque option est indépendante et désactivée par défaut — aucun changement
    de comportement pour les stratégies existantes. Activable via
    `chunking_strategies.params` jsonb, une clé à la fois.
    """

    clean_content: bool = False
    strip_separators: bool = False
    strip_boilerplate: bool = False
    strip_html: bool = False

    @property
    def any_enabled(self) -> bool:
        return (
            self.clean_content or self.strip_separators or self.strip_boilerplate or self.strip_html
        )


class CleaningChunkerWrapper:
    """Applique les nettoyages configurés avant de déléguer au chunker interne.

    Implémente `StructuredChunkerProtocol`. Sans `options`, se comporte comme
    l'ancienne version (clean_content=True) pour la rétro-compatibilité.

    Ordre d'application : strip_html → clean_content → strip_separators → strip_boilerplate.
    """

    def __init__(
        self, inner: StructuredChunkerProtocol, options: CleaningOptions | None = None
    ) -> None:
        self._inner = inner
        self._options = options if options is not None else CleaningOptions(clean_content=True)

    def chunk(self, content: str) -> ChunkedDocument:
        opts = self._options
        if opts.strip_html:
            content = strip_html_tags(content)
        if opts.clean_content:
            content = clean_content_text(content)
        if opts.strip_separators:
            content = strip_decorative_separators(content)
        if opts.strip_boilerplate:
            content = strip_boilerplate_lines(content)
        return self._inner.chunk(content)
